module.exports = {
  getUsers: require('./getUsers'),
  getUser: require('./getUser'),
  getSpots: require('./getSpots'),
  getUserCreatedSpots: require('./getUserCreatedSpots'),
  getUserBookmarkedSpots: require('./getUserBookmarkedSpots'),
  deleteUser: require('./createUser'),
  createUser: require('./createUser'),
  createSpot: require('./createSpot'),
  deleteSpot: require('./deleteSpot'),
  createBookmark: require('./createBookmark'),
  deleteBookmark: require('./deleteBookmark'),
  getUser: require('./getUser'),
  login: require('./login'),
};
